# Generated by Django 3.2.18 on 2023-05-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_description_post_dish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dish',
            new_name='excerpt',
        ),
    ]
