# Generated by Django 3.2.18 on 2023-04-12 23:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
