# Generated by Django 3.2.18 on 2023-05-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_addmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddModel',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default='Published'),
        ),
    ]
