# Generated by Django 3.2.18 on 2023-05-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='excerpt',
            new_name='recipe',
        ),
    ]
