# Generated by Django 3.2.18 on 2023-05-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_slug_post_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='slug',
        ),
    ]
